### ISSUE TITLE
WPGlobus 1.5.0 and Redux Framework are annoing

### ISSUE THREAD

**Issue by yurikalmykov** [reduxframework/docs.redux.io#2]
Installed WPGlobus 1.5.0 plugin in my wordpress and see now an idiot warning on my admin pages, linked here, moreover it didn't disappear after I closed it once:

> Redux Framework: New Documentation coming!
> We've heard your screams and we're completely redoing our documentation. For a preview of things to come, please visit our new docs repo. P.S. You can contribute! If you have an idea for a doc, post your ideas here.

I don't care about Redux Framework or anything else, I care about my admin page. So go to hell both framework and that plugin.

**Comment by kprovance** [comment]
A little civility might be in order here.  In fact, no.  I'm deleting your message.  If you cannot post with a little respect, then no one is going to go out of their way to assist you.
