### ISSUE TITLE
missing theme options after cloning the website (files and db) to staging server

### ISSUE THREAD

**Issue by Oglomuntonido** [reduxframework/docs.redux.io#5]
help appreciated

**Comment by dovy** [comment]
Sorry, but we can't help with server issues. That's beyond the scope of our project.

**Comment by Oglomuntonido** [comment]
I appreciate the feedback but I don't think it is a server issue. I think the documentation on migrating the sites powered by Redux is insufficient. Regards.

**Comment by dovy** [comment]
These docs are beta. We need to update them, hah.

**Comment by Oglomuntonido** [comment]
:-)
